---
datasets:
- ice_hockey
- openweather
- owid
- gsmarena
- wikidata
default_dataset: ice_hockey
debug: true
host_prefix: ""
cache_dev_splits: false
generated_outputs_dir: ../outputs
pipelines:
  export:
    pipeline: export
    interactive: false
